config/routes.rb
Rails.application.routes.draw do
	root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kitten.rb
class Kitten < ApplicationRecord
	validates :name, presence: true,
									 length: { maximum: 50 }
	validates :age,      presence: true
	validates :cuteness, presence: true
	validates :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController

	def index
		@kittens = Kitten.all
		respond_to do |format|
			format.html
			format.json { render json: @kittens.to_json }
		end
	end

	def show
		@kitten = Kitten.find(params[:id])
		respond_to do |format|
			format.html
			format.json { render json: @kitten.to_json }
		end
	end

	def new
		@kitten = Kitten.new
	end

	def create
		@kitten = Kitten.new(kitten_params)
		if @kitten.save
			flash[:success] = "New kitten created"
			redirect_to root_url
		else
			render :new
		end
	end

	def edit
		@kitten = Kitten.find(params[:id])
	end

	def update
		@kitten = Kitten.find(params[:id])
		if @kitten.update_attributes(kitten_params)
			flash[:success] = "Kitten updated"
			redirect_to root_url
		else
			render :edit
		end
	end

	def destroy
		@kitten = Kitten.find(params[:id]).destroy
		flash[:success] = "Kitten deleted!"
		redirect_to root_url
	end

	private

	def kitten_params
		params.require(:kitten).permit(:name, :age, :cuteness, :softness)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_for(@kitten) do |f| %>
	<% if @kitten.errors.any? %>
	<span>The form contains <%= pluralize(@kitten.errors.count, "error") %>.</span><br>
	<span>You should probably deal with your cat problem(bahaha)</span>
	<% end %><br>
	<%= f.label :name %>
	<%= f.text_field :name %>
	<%= f.label :age %>
	<%= f.number_field :age, in: 0..40, step: 1 %>
	<%= f.label :cuteness %>
	<%= f.number_field :cuteness, in: 1..10, step: 1 %>
	<%= f.label :softness %>
	<%= f.number_field :softness, in: 1..10, step: 1 %>
	<%= f.submit "SUBMIT" %>
<% end %>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>
<%= render "form" %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
	<%= @kittens.each do |kitten| %>
		<li>
			Name: <%= kitten.name %><br>
			Age: <%= kitten.age %><br>
			Cuteness: <%= kitten.cuteness %><br>
			Softness: <%= kitten.softness %><br>
			<%= link_to "Show kitten", kitten_path(kitten) %><br>
			<%= link_to "Edit kitten", edit_kitten_path(kitten) %><br>
			<%= link_to "Delete kitten", kitten, method: :delete %>
		</li><br><span>-------------------------------------</span><br>
	<% end %>
</ul>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>
<%= render "form" %>

app/views/kittens/show.html.erb
<h1>Kitten</h1>
<p>
	Name: <%= @kitten.name %><br>
	Age: <%= @kitten.age %><br>
	Cuteness: <%= @kitten.cuteness %><br>
	Softness: <%= @kitten.softness %><br>
	<%= link_to "Edit kitten", edit_kitten_path(@kitten) %><br>
	<%= link_to "Delete kitten", @kitten, method: :delete %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <ul>
  <li><%= link_to "Home", root_path %></li>
  <li><%= link_to "New Kitten", new_kitten_path %></li>
	</ul>
  <body>
    <%= yield %>
  </body>
</html>